#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: minimal
title: config的标题
author: config的作者
description: config的描述
